spring.application.name=HomeServerAPI
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=
spring.jpa.properties.hibernate.default_schema=public
#logging.level.org.springframework=DEBUG
